name: Update version and release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/release.yml'
  # workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: snap
        run: |
          mkdir -m 777 gen
          docker run -i --init --cap-add=SYS_ADMIN -v ./gen:/home/pptruser/gen ghcr.io/puppeteer/puppeteer:latest node -e "$(cat snapshot.js)" https://cv.bnei.dev ./gen
          mv gen/* snapshots/
          git commit -s -m "snapshot {{ github.sha }}"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: snapshot
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          # persist-credentials: false
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: release-it
        run: |
          npm install --no-save --force release-it @release-it/conventional-changelog
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
