name: Update version and release

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/release.yml'
  # workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
  
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: true
          version: 8
      
          

      - name: Compress node_modues
        run: tar -cf node_modules.tar.gz node_modules

      - name: 'Upload Node Modules'
        uses: actions/upload-artifact@v3
        with:
          name: node_modules.tar.gz
          path: node_modules.tar.gz
          retention-days: 1
      
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: pnpm build

      - name: Install PM2
        run: npm install pm2 -g
      - name: Start server
        run: |
          NODE_PORT=4173 pm2 start build
          sleep 5

      - name: snap
        run: |
          mkdir -m 777 gen
          docker run -i --init --cap-add=SYS_ADMIN -v ./gen:/home/pptruser/gen ghcr.io/puppeteer/puppeteer:latest node -e "$(cat snapshot.js)" http://localhost:4173 ./gen
          mv gen/* static/
          git add static
          git commit -s -m "snapshot ${{ github.sha }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy:
    runs-on: ubuntu-latest
    needs: snapshot
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          ref: 'main'

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: node_modules.tar.gz

      - name: Decompress node_modules
        run: tar -xf node_modules.tar.gz

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: snapshot
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: 'main'

          # persist-credentials: false
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: release-it
        run: |
          git pull
          npm install --no-save --force release-it @release-it/conventional-changelog
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
