name: Update version and release

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/release.yml'
  # workflow_dispatch:

jobs:
  deploy-snapshot-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false
          version: 8

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}


      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: snap
        run: |
          mkdir -m 777 gen
          docker run -i --init --cap-add=SYS_ADMIN -v ./gen:/home/pptruser/gen ghcr.io/puppeteer/puppeteer:latest node -e "$(cat snapshot.js)" https://cv.bnei.dev ./gen
          mv gen/* static/
          git add static
          git commit -s -m "snapshot ${{ github.sha }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: deploy-snapshot-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          # persist-credentials: false
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: release-it
        run: |
          git pull
          npm install --no-save --force release-it @release-it/conventional-changelog
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
